name = "framewise_cli"
description = "framewise command-line front end"
executables = ["framewise_cli"]
version = "0.1.0-dev"
authors = ["Olivier Henley"]
maintainers = ["Olivier Henley <henley@adacore.com>"]
maintainers-logins = ["ohenley"]
licenses = "Apache-2.0"

project-files = ["cli.gpr"]

[[depends-on]]
framewise = "*"

[[pins]]
framewise = { path = ".." }
